name: Sync Fork

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:        # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        uses: tgymnich/fork-sync@v1.2.1
        with:
          owner: spostnova
          base: main
          head: main
          github_token: ${{ secrets.GITHUB_TOKEN }}